### ISSUE TITLE
Is it possible to use http transcoding without google cloud platform?

### ISSUE THREAD

**Issue by Rchan0100** [GoogleCloudPlatform/nodejs-docs-samples#1927] opened 2020-07-18 16:02 UTC
Sorry for the basic question (I'm new with gRPC).
Is it possible to use http transcoding without google cloud platform & endpoints?

I'm currently trying to create a mock-application and we are trying to have some sort of frontend with a UI (or can go headless browser in the beg.) that can send HTTP requests to the Extensible Service Proxy, and then ESP will transcode the HTTP request to HTTP2 so that it can be sent as a request to our gRPC services. I think K8s is a bit overkill since we'll only have a few containers (and not too familiar with deployment in k8s). 

I'm trying to just use grpc-node, and want to do http mapping in ESP.
Can we just import <import "google/api/annotations.proto";> into our protofile and get this functionality of HTTP mapping?

**Comment by fhinkel** [comment] 2020-07-20 10:01
Hi @Rchan0100 , thank you for the detailed issue. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this issue to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's gRPC tag](https://stackoverflow.com/questions/tagged/grpc) is most appropriate for design and general troubleshooting. You can read more about community support [here](https://cloud.google.com/support/docs/community).
* [Google Cloud's public issue tracker](https://cloud.google.com/support/docs/issue-trackers) is most appropriate for bugs and unexpected behavior.
* [Google Cloud Support](https://cloud.google.com/support/) is most appropriate if you have an existing support contract with Google.

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2020-07-20 10:01 UTC
Labels: type: question
