### ISSUE TITLE
Presubmit for run/markdown-preview/editor is consistently  failing

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#1791] opened 2020-05-07 14:16 UTC
https://source.cloud.google.com/results/invocations/32813175-423a-4ddf-9065-e7da9f31cea5/targets
https://source.cloud.google.com/results/invocations/e393577d-e306-4540-b4c9-141aea0747f4/targets

**Comment by grayside** [comment] 2020-05-20 17:16
Note that a CL was submitted enabling Kokoro testing for a sample still in development. This will be fixed in #1752.

**Comment by grayside** [comment] 2020-05-20 17:17
Not sure what priority this has, but adjusting the labels to indicate this bug only exists as a flag to indicate this test failure can be ignored.

**Comment by averikitsch** [comment] 2020-05-20 17:26
I assume we will be able to merge this sample at least by next week. Though an option would be to revert the CL.

**Comment by grayside** [comment] 2020-06-15 21:37
Duplicate of #1877 and #1878

**Closed by grayside** 2020-06-15 21:37 UTC
Labels: api: run, priority: p2, type: cleanup
