### ISSUE TITLE
Use Node.js to call Google API and put it into a cloud function. client method cannot return data

### ISSUE THREAD

**Issue by radianceltd** [GoogleCloudPlatform/nodejs-docs-samples#1584] opened 2020-01-09 08:33 UTC
`exports.devicegetway = async (req,res) => {
    
    const cloudRegion = 'us-central1';
    const gatewayId = 'my-region-001';
    const projectId = 'riltmw025tool-2019';
    const registryId = 'my-registry-006s';

    const client = getClient('riltmw025tool-2019-21396a54b9be.json');
    listDevicesForGateway(client, projectId, cloudRegion, registryId, gatewayId);
}

const getClient = async (serviceAccountJson,res) => {
    const authClient = await google.auth.getClient({
        keyFilename: serviceAccountJson,
        scopes: ['https://www.googleapis.com/auth/cloud-platform'],
    });
    const discoveryUrl = 'https://cloudiot.googleapis.com/v1/projects/riltmw025tool-2019/locations/us-central1/registries/my-registry/devices';
    google.options({
        auth: authClient,
    });
    try {
        return google.discoverAPI(discoveryUrl);
    } catch (err) {
        console.error('Error during API discovery.', err);
    }
};

const listDevicesForGateway = async (client,projectId,cloudRegion,registryId,gatewayId) => {
    const parentName = `projects/${projectId}/locations/${cloudRegion}/registries/${registryId}`;
    const request = {
        parent: parentName,
        'gatewayListOptions.associationsGatewayId': gatewayId,
    };
    let devices;
    try {
        const {data} = await client.projects.locations.registries.devices.list(
            request
        );
        devices = data.devices;
    } catch (err) {
        console.error('Could not list devices', err);
        return;
    }
    console.log('Current devices bound to gateway: ', gatewayId);
    if (devices && devices.length > 0) {
        devices.forEach(device => {
            console.log(`\tDevice: ${device.numId} : ${device.id}`);
        });
    } else {
        console.log('No devices bound to this gateway.');
    }
};
`
const {data} = await client.projects.locations.registries.devices.lis cannot return data

I try to use const client = new iot.v1.DeviceManagerClient to get only part of the API function data

IAM and service account / valid key are both stored in the project file, but this problem never returns to me

**Comment by radianceltd** [comment] 2020-01-09 08:36
@radianceltd @beccasaurus @proppy @broady @chingor13

**Comment by radianceltd** [comment] 2020-01-09 08:39
@gguuss

**Comment by radianceltd** [comment] 2020-01-09 08:46
@jmdobry @ace-n @renovate-bot @fhinkel @nareshqlogic @JustinBeckwith @michaelawyu @noerog @hongalex

**Comment by fhinkel** [comment] 2020-01-09 15:18
Hi @radianceltd, thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google IoT tag](https://stackoverflow.com/tags/google-cloud-iot) is most appropriate for design and general troubleshooting. You can read more about community support [here](https://cloud.google.com/support/docs/community).
* [Google Cloud's public issue tracker](https://cloud.google.com/support/docs/issue-trackers) is most appropriate for bugs and unexpected behavior.
* [Google Cloud Support](https://cloud.google.com/support/) is most appropriate if you have an existing support contract with Google.

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2020-01-09 15:18 UTC

**Comment by radianceltd** [comment] 2020-01-10 00:15
@fhinkel  Thank you for your reply, would you like to inquire whether Google has restricted Chinese computers from reading data through VPN nodes?
