### ISSUE TITLE
nodejs-docs-samples/functions/scheduleinstance/ won't start all VMs

### ISSUE THREAD

**Issue by fhinkel** [GoogleCloudPlatform/nodejs-docs-samples#2157] opened 2021-02-08 21:29 UTC
Copied over from https://github.com/googleapis/nodejs-compute/issues/485

1) Is this a client library issue or a product issue?
Sry, i have no idea what that means

#### Environment details

  - OS: Debian 10
  - Node.js version: 10
  - npm version: didn't use. I stay in a browser
  - `@google-cloud/compute` version: ^2.0.0

#### Steps to reproduce

  1. Create at least 2 VMs across different regions or zones
  2. Use the examples from https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/functions/scheduleinstance
  3. Make and run the jobs to ping a restart of the VMs
  4. Check the log for each individual VM. Most, if not all, will not show anything that indicates a restart was triggered. For some reason, only my VMs that were created before early July will restart.

#### Things to note:

  A. after [vms].map = async... by checking vms.length, looks like it's 0 for anytime the label is unique for a VM that has a zone different from where the job scheduler lives
  B. Replacing line 38 with const options = {filter: ``};  leads to desired results.
  C. line 101 seems to output the success message even if the contents of the if statement don't execute.

**Comment by ace-n** [comment] 2021-02-08 21:32
@fhinkel this isn't a "pure" `functions/` sample - reassigned to @askmeegs accordingly.

**Comment by averikitsch** [comment] 2021-02-27 01:08
The sample is working as intended. The sample and tutorial specifies filtering VMs by the zone specified in the Pub/Sub message.

**Closed by averikitsch** 2021-02-27 01:08 UTC
Labels: :rotating_light:, api: cloudfunctions, priority: p1, samples, type: bug
