### ISSUE TITLE
Question: how to debug issues loading http://localhost:8080

### ISSUE THREAD

**Issue by topshef** [GoogleCloudPlatform/nodejs-docs-samples#1757] opened 2020-04-28 21:43 UTC
hi, this is not an issue with the code, so if this is the wrong place to post, please redirect me and close this.

I'm able to run through the tutorial demo app which works when I deploy it, but I'm unable to run it locally for testing via http://localhost:8080 
On Windows 10 neither in Chrome nor Edge browser, just the standard "This site can’t be reached"

Many thanks for any help or pointers.

**Comment by fhinkel** [comment] 2020-04-29 20:01
Hi @topshef, thank you for opening an issue. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google Cloud Platform tag](https://stackoverflow.com/questions/tagged/google-cloud-platform) is most appropriate for design and general troubleshooting. You can read more about community support [here](https://cloud.google.com/support/docs/community).
* [Google Cloud's public issue tracker](https://cloud.google.com/support/docs/issue-trackers) is most appropriate for bugs and unexpected behavior.
* [Google Cloud Support](https://cloud.google.com/support/) is most appropriate if you have an existing support contract with Google.

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2020-04-29 20:01 UTC
Labels: triage me

**Comment by topshef** [comment] 2020-05-14 17:24
For anyone else landing here with this problem, a solution was found thanks to this post:
https://medium.com/google-cloud/no-localhost-no-problem-using-google-cloud-shell-as-my-full-time-development-environment-22d5a1942439

I have suggested to google to update the documentation as follows:
https://cloud.google.com/appengine/docs/standard/nodejs/building-app/writing-web-service#running_the_server_locally

Replace step 2 with:
Click the web preview icon:
https://miro.medium.com/max/1400/1*1WiC7L2mV_x16geFpwoYkQ.gif
