### ISSUE TITLE
Null value error getting client

### ISSUE THREAD

**Issue by radianceltd** [GoogleCloudPlatform/nodejs-docs-samples#1581] opened 2020-01-07 02:44 UTC
I use the following code to get the client：
```
// [START iot_get_client]
// Returns an authorized API client by discovering the Cloud IoT Core API with
// the provided API key.
const getClient = async serviceAccountJson => {
  // the getClient method looks for the GCLOUD_PROJECT and GOOGLE_APPLICATION_CREDENTIALS
  // environment variables if serviceAccountJson is not passed in
  const authClient = await google.auth.getClient({
    keyFilename: serviceAccountJson,
    scopes: ['https://www.googleapis.com/auth/cloud-platform'],
  });

  const discoveryUrl = `${DISCOVERY_API}?version=${API_VERSION}`;

  google.options({
    auth: authClient,
  });

  try {
    return google.discoverAPI(discoveryUrl);
  } catch (err) {
    console.error('Error during API discovery.', err);
  }
};
// [END iot_get_client]

```
When I read the client API, Getclient returned to me like this, I don't know how to call const {data} = await client.projects.locations.registries.devices.list (request); the data data

![image](https://user-images.githubusercontent.com/58924597/71864288-6a545f80-313a-11ea-9498-ad2c19fa7cfb.png)

I don't know why this code doesn't work。

If the above client code fails to run, the following code will fail to run

![image](https://user-images.githubusercontent.com/58924597/71864472-d5059b00-313a-11ea-9774-1457021548dd.png)

Help me to analyze the reason.

**Comment by hongalex** [comment] 2020-01-09 02:12
I believe this a duplicate of issue #1579

**Closed by hongalex** 2020-01-09 02:12 UTC
Labels: type: question
