### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by biligeny** [GoogleCloudPlatform/nodejs-docs-samples#2207] opened 2021-03-21 02:06 UTC
seems node version need to be adjusted to 12.14.1 in order to pass following error.

ERROR: (gcloud.app.deploy) Cloud build failed. Check logs at https://console.cloud.google.com/cloud-build/builds/8cdb2233-6cb4-40e2-b202-8a9983f104c9?project=523099165473 Failure status: UNKNOWN: Error Response: [2] Build failed; check build logs 
for details

**Comment by dylanmpeck** [comment] 2021-03-22 19:03
Can confirm - we have a Qwiklab which follows the walkthrough in the appengine flexible [hello world sample](https://github.com/GoogleCloudPlatform/nodejs-docs-samples/tree/master/appengine/hello-world/flexible) and app engine deployment does not work without changing the Node version in package.json to >= 12.14.1.

We get this error without it:

`gpg: Can't check signature: public key not found
The Node.js binary could not be verified.
This means it may not be an officially released Node.js binary
or may have been tampered with.

Aborting the installation.`

**Comment by fhinkel** [comment] 2021-03-23 14:42
@michaelawyu Please have a look

**Comment by ace-n** [comment] 2021-03-29 18:37
@fhinkel I can take this.

I'm wondering if we should accelerate #2151, since that upgrades everything to Node 14?

**Comment by engelke** [comment] 2021-03-29 19:29
I've confirmed that the hello-world sample fails in App Engine Flex with either Node 12 or 14, but works correctly in standard with either of those versions. I'll pursue this further.

**Comment by averikitsch** [comment] 2021-07-21 17:56
I am unable to reproduce this error, so I expect any issues with the internal build has been fixed. Can you confirm that you are still experiencing this issue?

**Comment by averikitsch** [comment] 2021-07-22 15:52
Closing. Please reopen if you are still experiencing issues.

**Closed by averikitsch** 2021-07-22 15:52 UTC
Labels: :rotating_light:, api: appengine, priority: p1, samples, type: bug
