### ISSUE TITLE
Not working sample: /appengine/websockets

### ISSUE THREAD

**Issue by artpolikarpov** [GoogleCloudPlatform/nodejs-docs-samples#292] opened 2017-01-09 22:39 UTC
When try on real servers:
> ERROR: (gcloud.app.deploy) INVALID_ARGUMENT: Deployments to App Engine Flexible require `env: flex` in app.yaml.  The `vm:true` setting has been depreca
ted. To learn more, please visit https://cloud.google.com/appengine/docs/flexible/python/upgrading.

**Comment by artpolikarpov** [comment] 2017-01-09 22:46
And also:
> INVALID_ARGUMENT: Forwarded ports configuration is not supported in App Engine Flexible Environment deployments

**Comment by jmdobry** [comment] 2017-01-09 22:56
Duplicate of #285

**Closed by jmdobry** 2017-01-09 22:56 UTC
Labels: duplicate
