### ISSUE TITLE
iot manager list command with null information 

### ISSUE THREAD

**Issue by Chgavilana** [GoogleCloudPlatform/nodejs-docs-samples#1973] opened 2020-09-12 10:25 UTC
Running 'node manager.js listDevices my-node-registry' , I get  list of my devices and more information, however, some information is null. for example:

```
Current devices in registry:
...
Device 3:  { credentials: [],
  metadata: {},
  id: 'pcTest',
  name: '',
  numId: '123456789123456',
  lastHeartbeatTime: null,
  lastEventTime: null,
  lastErrorTime: null,
  lastErrorStatus: null,
  config: null,
  lastConfigAckTime: null,
  state: null,
  lastConfigSendTime: null,
  blocked: false,
  lastStateTime: null,
  logLevel: 'LOG_LEVEL_UNSPECIFIED',
  gatewayConfig: null }
Device 4:  { credentials: [],
  metadata: {},
  id: 'pcTest2',
  name: '',
  numId: '123456789123456',
  lastHeartbeatTime: null,
  lastEventTime: null,
  lastErrorTime: null,
  lastErrorStatus: null,
  config: null,
  lastConfigAckTime: null,
  state: null,
  lastConfigSendTime: null,
  blocked: false,
  lastStateTime: null,
  logLevel: 'LOG_LEVEL_UNSPECIFIED',
  gatewayConfig: null }

```
Why some parameters are null if have information over google cloud platform like heartbeat time? is a problem of IAM permission or is a limit over API?
thks

**Comment by sofisl** [comment] 2020-09-14 17:32
Hi there! Would you mind sharing your code to triage the issue? Thanks!

**Comment by Chgavilana** [comment] 2020-09-14 17:55
Hi:
Code is the example code from iot/manager from this repository. I just use the command with my repository parameters.

**Comment by sofisl** [comment] 2020-09-17 18:22
Hi @Chgavilana,

Without knowing how many devices or requests you've made, I can't say for sure if it's a quota issue. I've linked the documentation [here](https://cloud.google.com/iot/quotas) just in case.

A couple of ideas I have off the top of my head are: (i) have you confirmed the devices are correctly recording the information, and are storing it? (ii) perhaps you needed to wait for the information to become available?

I'm also involving @sgreenberg who may know more!

**Comment by munkhuushmgl** [comment] 2020-09-17 20:00
@Chgavilana It is working as intended. have nothing to do with IAM. It just indicates that these variables are not initialized.

**Comment by Chgavilana** [comment] 2020-09-17 20:58
hi:
Attached I send 3 images: first one is the command listdevice (and reason of this ticket); second one is getdevice that show information about devices and get data information, for example lastheartbeatTime; and finally a screenshot over gcp where I can confirm that data exists.

I need a API that check if all my devices is alive (without send any additional state or telemetry message, just mqtt alive ping alias heartbeat), and listdevices is my best option, and my second option is use listdevices to get all devices and check one by one with getdevice. I check the example code and it is fine, for this reason a think that maybe is a problem over gcp or google API.

What do you think, google API could be the problem? 

![listdevices](https://user-images.githubusercontent.com/5751704/93524456-21c08900-f8fa-11ea-9368-d0f818d35d21.png)
![getdevices](https://user-images.githubusercontent.com/5751704/93524462-238a4c80-f8fa-11ea-8561-6669a3c2aa1a.png)
![gcp](https://user-images.githubusercontent.com/5751704/93524464-238a4c80-f8fa-11ea-86fd-c1705439ef42.png)

**Comment by munkhuushmgl** [comment] 2020-09-17 21:01
@Chgavilana Hmmm, you are right. Let me investigate a bit on more whether it is service related or sample related.

**Comment by fhinkel** [comment] 2020-11-06 08:04
Looks like you were able to resolve the issue. Closing, please re-open if needed.

**Closed by fhinkel** 2020-11-06 08:04 UTC
Labels: api: cloudiot, needs more info, samples, type: question
