### ISSUE TITLE
Core IoT/MQTT Device Disconnected

### ISSUE THREAD

**Issue by tripflex** [GoogleCloudPlatform/nodejs-docs-samples#1150] opened 2019-02-15 21:22 UTC
I can't seem to get any response from Sales or Support regarding this, and every other IoT service provider has a feature to do this, how does Google IoT offering not?!

https://stackoverflow.com/questions/54609757/google-core-iot-device-offline-event-or-connection-status

Makes me wish I hadn't put my faith in Google to provide IoT services if it can't even support device disconnect events ... even having LWT would handle this, but doesn't seem to be an option.   I'm hoping to generate some kind of response for this as nobody seems to be able to answer my question.

**Comment by fhinkel** [comment] 2019-02-28 11:45
Hi @tripflex, thank you for the detailed bug report. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

* [StackOverflow's Google IoT tag](https://stackoverflow.com/tags/google-cloud-iot) is most appropriate for design and general troubleshooting. You can read more about community support [here](https://cloud.google.com/support/docs/community).
* [Google Cloud's public issue tracker](https://cloud.google.com/support/docs/issue-trackers) is most appropriate for bugs and unexpected behavior.
* [Google Cloud Support](https://cloud.google.com/support/) is most appropriate if you have an existing support contract with Google.

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2019-02-28 11:45 UTC
