### ISSUE TITLE
SEND EMAIL NOTIFICATIONS AT GOOGLE CLOUD FUNCTIONS TRIGGERED BY PUB/SUB?

### ISSUE THREAD

**Issue by jesuspisa** [GoogleCloudPlatform/nodejs-docs-samples#1191] opened 2019-03-01 12:53 UTC
Hi,

I want to check the temperature value from the message received from Pub/Sub in JSON format.

And if the temperature data is higher than 23 , send an email notification.

How can I do that?

**Comment by fhinkel** [comment] 2019-03-02 02:52
Hi @jesuspisa , thank you for opening an issue. Unfortunately, this issue tracker has limited visibility and scope - basically, it's just for reporting issues with the samples contained here and is only watched by the folks who work on these samples.

We are happy to help you move this bug to venues where it'll get the attention of the appropriate product teams.

- [StackOverflow's Google Pubsub](https://stackoverflow.com/questions/tagged/google-cloud-pubsub) tag is most appropriate for design and general troubleshooting. You can read more about community support [here](https://cloud.google.com/support/docs/community).
- [Google Cloud's public issue tracker](https://cloud.google.com/support/docs/issue-trackers) is most appropriate for bugs and unexpected behavior.
- [Google Cloud Support](https://cloud.google.com/support/) is most appropriate if you have an existing support contract with Google.

I'm going to close this issue because the folks who own this repo have no actionable way to resolve it directly, but please let us know if there's anything we can do to help!

**Closed by fhinkel** 2019-03-02 02:52 UTC
