### ISSUE TITLE
functions/billing: test failure with non-actionable messages

### ISSUE THREAD

**Issue by grayside** [GoogleCloudPlatform/nodejs-docs-samples#1565] opened 2019-12-12 17:59 UTC
Two tests have this same failure state, which prevents effective triage.

1. The tests need to be fixed
2. The test needs to surface the underlying error.

Currently blocking merge on #1515

```
  functions/billing tests
    notifies Slack
      functions_billing_slack
        ✓ should notify Slack when budget is exceeded (868ms)
    disables billing
      functions_billing_stop
(node:61) UnhandledPromiseRejectionWarning: ChildProcessError: Command failed: functions-framework --target=notifySlack --signature-type=event --port 8080
 `functions-framework --target=notifySlack --signature-type=event --port 8080` (exited with error code null)
    at callback (/tmpfs/src/github/nodejs-docs-samples/functions/billing/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:288:5)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:61) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:61) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
        1) should disable billing when budget is exceeded
```

**Comment by fhinkel** [comment] 2019-12-20 21:06
@ace-n Can you have a look at this functions tests please. Thanks

**Comment by ace-n** [comment] 2020-05-21 23:28
Closing this as outdated as #1515 has since been merged.

@fhinkel @grayside please reopen if I'm wrong. Thanks! 🙂

**Comment by grant** [comment] 2020-09-28 17:50
@ace-n Seeing this error consistently and am unable to merge an unrelated PR: https://github.com/GoogleCloudPlatform/nodejs-docs-samples/pull/1986

```
1 failing

  1) functions/billing tests
       disables billing
         functions_billing_stop
           should disable billing when budget is exceeded:

      AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:

  assert.ok(response.body.includes('Billing disabled'))

      + expected - actual

      -false
      +true

      at Context.it (test/index.test.js:131:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)



(node:54) UnhandledPromiseRejectionWarning: ChildProcessError: Command failed: functions-framework --target=stopBilling --signature-type=event --port 8081
Error: Invalid Credentials
    at Gaxios._request (/tmpfs/src/github/nodejs-docs-samples/functions/billing/node_modules/gaxios/build/src/gaxios.js:89:23)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 `functions-framework --target=stopBilling --signature-type=event --port 8081` (exited with error code null)
    at callback (/tmpfs/src/github/nodejs-docs-samples/functions/billing/node_modules/child-process-promise/lib/index.js:33:27)
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:198:13)
    at maybeClose (internal/child_process.js:982:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
(node:54) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cloud-functions-billing@0.0.1 test: `mocha test/index.test.js --timeout=5000`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cloud-functions-billing@0.0.1 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2020-09-28T05_41_14_227Z-debug.log
```

Can we make this test, `Internal CI (functions/billing)`, not required to merge a PR?

**Comment by engelke** [comment] 2020-09-28 21:15
Me too for PR #1985

**Comment by ace-n** [comment] 2020-09-28 21:32
I've marked this test as *optional*, and am planning to investigate the
failure (in further detail) later today.

**Comment by ace-n** [comment] 2020-09-29 04:08
Update: looks like this test is outdated - it depends on `hasScopes`, which doesn't exist on my local machine (and is causing the test to fail).

@JustinBeckwith I wasn't able to find a replacement in either of the [`google-auth`](https://github.com/googleapis/google-auth-library-nodejs/search?q=hasScopes)  or [`googleapis`](https://github.com/googleapis/google-api-nodejs-client/search?q=hasScopes) Node.js libraries. How should I replace this? 😕

**Comment by JustinBeckwith** [comment] 2020-09-29 04:59
I think you're looking for something like this:

```js
const {GoogleAuth} = require('google-auth-library');
const auth = new GoogleAuth({
  scopes: [
    'https://www.googleapis.com/auth/cloud-billing',
    'https://www.googleapis.com/auth/cloud-platform',
  ],
});
google.options({auth});
```

**Comment by ace-n** [comment] 2020-10-07 04:25
Closing as duplicate of #1988 (which was fixed just now anyway).

**Closed by ace-n** 2020-10-07 04:25 UTC
Labels: :rotating_light:, api: cloudfunctions, priority: p1, samples, type: bug
