### ISSUE TITLE
google-auth-library is not working on client side

### ISSUE THREAD

**Issue by oleg-mir** [GoogleCloudPlatform/nodejs-docs-samples#3594] opened 2023-12-17 22:13 UTC
Hi, 
in your example here https://cloud.google.com/run/docs/tutorials/secure-services
it is shown as FE-BE services, however the "editor" it not a FE but a node service
https://github.com/GoogleCloudPlatform/nodejs-docs-samples/blob/ebc7aca48f8cc493d73566621ca621af4764c006/run/markdown-preview/editor/Dockerfile

google-auth-library can't run in a browser and will not work authenticating the FE service against BE.

this is very bad and wrong tutorial that supposed to show FE-BE (and states that in a diagram) but showing BE-BE

where can i find an example of real FE (e.g react) that tries to access private BE service?

Thanks, Oleg.

**Comment by pattishin** [comment] 2024-03-08 04:47
@oleg-mir Thank you for creating this issue. If you are looking for how to deploy a frontend single page app (like React) in Cloud Run accessing another Cloud Run service read through this tutorial: https://www.googlecloudcommunity.com/gc/Community-Blogs/No-servers-no-problem-A-guide-to-deploying-your-React/ba-p/690760. Closing as the sample is working as intended using two cloud run services leveraging node express.

**Closed by pattishin** 2024-03-08 04:47 UTC
Labels: type: bug, triage me, priority: p2, samples
